
- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Remove Old Content
  ansible.builtin.user:
    name: /app
    state: absent

- name: Create App Directory
  ansible.builtin.user:
    name: /app
    state: directory

- name: Download and Extract Application Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes