
- name: Disable Nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable Nodejs
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install Nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed
    enabled: yes

- name: App Pre-requisites
  ansible.builtin.import_tasks: app-preq.yml

- name: Download Nodejs Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Schema Setup
  ansible.builtin.import_tasks: mongo-schema.yml
#  when: schema is defined

- name: SystemD Setup
  ansible.builtin.import_tasks: systemd-setup.yml




